# Generated by Django 2.2 on 2019-05-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190423_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default_Name', max_length=150)),
                ('email', models.CharField(default='Default@gmail.com', max_length=200)),
                ('phone', models.CharField(default='0000000000000', max_length=50)),
                ('textarea', models.CharField(default='Default_textarea', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='static/shop/test.jpg', max_length=300),
        ),
    ]
