# Generated by Django 2.2 on 2019-05-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190503_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(default='No Item', max_length=500)),
                ('ttl', models.CharField(default='total', max_length=20)),
                ('name', models.CharField(default='order_name', max_length=50)),
                ('email', models.CharField(default='order_email', max_length=100)),
                ('address', models.CharField(default='order_address', max_length=300)),
                ('country', models.CharField(default='order_country', max_length=50)),
                ('city', models.CharField(default='order_city', max_length=50)),
                ('state', models.CharField(default='order_state', max_length=50)),
                ('zip', models.CharField(default='order_zip', max_length=20)),
                ('phone', models.CharField(default='order_phone', max_length=50)),
            ],
        ),
    ]
